### ISSUE TITLE
Minor typo in FF18 Few-Shot Report

### ISSUE THREAD

**Issue by andrewrreed** [fastforwardlabs/mdffreport18#2]
### Minor Typo
- The intro paragraph refers to the STS report, though the links _are_ correct: 
![image](https://user-images.githubusercontent.com/23462538/116246392-f3c8e000-a737-11eb-9f01-9a8c9a4b5bfa.png)

**Comment by andrewrreed** [comment]
@melaniebeck No rush on this, but noticed a reference to the STS report while reviewing FF18 - documenting here for whenever you can get to it!

**Comment by cjwallace** [comment]
Good spot! Fixed (9c29a8e) and deployed.
